/* eslint-disable */
// This file is generated by scripts/sync-constants.ts
// Source of truth: programs/catallaxyz/src/constants.rs

export const USDC_DECIMALS = 6;
export const OUTCOME_YES = 0;
export const OUTCOME_NO = 1;
export const PRICE_SCALE = 1_000_000;
export const INACTIVITY_TIMEOUT_SECONDS = 7 * 24 * 60 * 60;
export const VRF_FEE_LAMPORTS = 5_000_000;
export const MARKET_CREATION_FEE = 10_000_000;
export const TERMINATION_EXECUTION_REWARD_USDC = 100_000;
