#!/bin/bash

# Admin panel quick setup script
# Admin Panel Quick Setup Script

set -e

echo "================================================"
echo "Catallaxyz Admin Panel Setup"
echo "================================================"
echo ""

# Check correct directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this script from the frontend directory"
    echo "Usage: cd /home/eero/Catallaxyz/frontend && bash setup-admin.sh"
    exit 1
fi

# Check Node.js
if ! command -v node &> /dev/null; then
    echo "❌ Error: Node.js is not installed"
    exit 1
fi

echo "✓ Node.js version: $(node -v)"
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  Warning: .env.local already exists"
    read -p "Do you want to overwrite it? (y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. You can manually edit .env.local"
        exit 0
    fi
fi

# Get admin wallet address
echo "================================================"
echo "Step 1: Configure Admin Wallet Address"
echo "================================================"
echo ""
echo "Please enter your admin wallet address:"
echo "(This address will have access to the admin panel)"
echo ""
read -p "Admin wallet address: " ADMIN_ADDRESS

# Validate address length (Solana addresses are usually 32-44 chars)
if [ -z "$ADMIN_ADDRESS" ]; then
    echo "❌ Error: Address cannot be empty"
    exit 1
fi

if [ ${#ADMIN_ADDRESS} -lt 32 ]; then
    echo "❌ Error: Invalid address (too short)"
    exit 1
fi

# Create .env.local file
echo ""
echo "Creating .env.local file..."
cat > .env.local << EOF
# ======================================
# Admin Configuration
# ======================================
# Generated by setup-admin.sh on $(date)

NEXT_PUBLIC_ADMIN_WALLET_ADDRESS=$ADMIN_ADDRESS

# ======================================
# Add your other environment variables below
# ======================================
EOF

echo "✓ .env.local created successfully"
echo ""

# Check dependencies
echo "================================================"
echo "Step 2: Check Dependencies"
echo "================================================"
echo ""

if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
    echo "✓ Dependencies installed"
else
    echo "✓ Dependencies already installed"
fi

echo ""

# Show next steps
echo "================================================"
echo "Setup Complete! 🎉"
echo "================================================"
echo ""
echo "Next steps:"
echo ""
echo "1. Start the development server:"
echo "   npm run dev"
echo ""
echo "2. Open your browser:"
echo "   http://localhost:3000"
echo ""
echo "3. Connect with your admin wallet:"
echo "   $ADMIN_ADDRESS"
echo ""
echo "4. Look for the 'Admin' button in the header"
echo ""
echo "5. Click the button to access the admin panel"
echo ""
echo "================================================"
echo "Documentation:"
echo "================================================"
echo ""
echo "- Admin Panel README: ADMIN_PANEL_README.md"
echo "- Setup Guide: ENV_ADMIN_SETUP.md"
echo "- Testing Guide: ADMIN_TESTING_GUIDE.md"
echo ""
echo "For help or issues, check the documentation above."
echo ""
echo "Happy administrating! 🛡️"
echo ""
