import fs from 'fs';
import path from 'path';

const ROOT = path.resolve('.');
const RUST_CONSTANTS = path.join(
  ROOT,
  'programs',
  'catallaxyz',
  'src',
  'constants.rs'
);
const OUTPUT = path.join(ROOT, 'shared', 'constants.ts');

const TARGETS = [
  'USDC_DECIMALS',
  'OUTCOME_YES',
  'OUTCOME_NO',
  'PRICE_SCALE',
  'INACTIVITY_TIMEOUT_SECONDS',
  'VRF_FEE_LAMPORTS',
  'MARKET_CREATION_FEE',
  'TERMINATION_EXECUTION_REWARD_USDC',
];

const rustSource = fs.readFileSync(RUST_CONSTANTS, 'utf8');

const extractValue = (name: string) => {
  const regex = new RegExp(`pub const\\s+${name}[^=]*=\\s*([^;]+);`);
  const match = rustSource.match(regex);
  if (!match) {
    throw new Error(`Missing constant ${name} in ${RUST_CONSTANTS}`);
  }
  return match[1].trim();
};

const lines = [
  '/* eslint-disable */',
  '// This file is generated by scripts/sync-constants.ts',
  '// Source of truth: programs/catallaxyz/src/constants.rs',
  '',
  ...TARGETS.map((name) => `export const ${name} = ${extractValue(name)};`),
  '',
];

fs.writeFileSync(OUTPUT, lines.join('\n'));
console.log(`Wrote ${OUTPUT}`);
